apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gke-ingress
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: prod-frontend
                port:
                  number: 80
          - backend:
              service:
                name: prod-backend
                port:
                  number: 80