apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
    namespace: default
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50