apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hello-apps
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http