apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: hello
    tier: frontend
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
      - name: gke-frontend-app
        image: europe-west1-docker.pkg.dev/cursos-imagina/imagina-registry-prod/gke-frontend-app:a29ebc9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
