apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: prod-
patchesStrategicMerge:
  - backend/deployment-values.yaml
  - backend/hpa-values.yaml
  - backend/pvc-values.yaml