apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  path: ./infrastructure/prod
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 15m
  timeout: 2m
  prune: true 
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-prometheus
  namespace: flux-system
spec:
  path: ./infrastructure/base/monitoring-prometheus
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: infrastructure
  interval: 15m
  timeout: 2m
  prune: true 
  wait: true