apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  type: NodePort
  ports:
  - name: web
    port: 3000
    protocol: TCP
    targetPort: web
  selector:
    grafana: grafana