apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  externalUrl: http://monitoring-k8s.ddns.net/prometheus
  serviceMonitoringSelector: {}
  serviceMonitoringNamespaceSelector: {}
  ruleSelector: {}
  ruleNamespaceSelector: {}
  resources:
    requests:
      memory: 400Mi