apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gke-ingress
  namespace: infrastructure
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - "*.curso-k8s.ddns.net"
    secretName: app-tls
  rules:
    - host: "*"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ""
                port:
                  number: 80