apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: v48.3.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  interval: 15m
  timeout: 5m
  releaseName: prometheus-operator
  install:
    remediation:
      retries: 3
  values:
    alertmanager:
      enabled: false